version: "3"
services:
  web:
    image: mdaraujo/gic_yolo_tf:latest
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
    ports:
      - "7700:5000"
    volumes:
      - /mnt/cifs13/yolo_tf/weights:/opt/weights
    networks:
      - webnet #Load-Balancer
networks:
  webnet:
