version: "3"
services:
  web:
    image: mdaraujo/gic_yolo_tf:latest
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
    ports:
      - "7700:5000"
    networks:
      - webnet
networks:
  webnet:
